import numpy as np
l = np.random.random(100)
print("Sum of l        :", np.sum(l))
print("Sum of l        :", sum(l))
big_array = np.random.rand(1000000)
print("Minimum of big_array :", np.min(big_array))
print("Minimum of big_array :", min(big_array))
print("Maximum of big_array :", np.max(big_array))
print("Maximum of big_array :", max(big_array))
print("Minimum , Maximum, Sum of big_array :", big_array.min(), big_array.max(), big_array.sum())
print("\n")
print("Multi Dimensional Aggregates\n")
m = np.random.random((3, 4))
print("m = \n", m)
print("Sum of m        :", np.sum(m))
print("Sum of m        :", sum(m))
print("Minimum along axis 0: ", m.min(axis=0))
print("Minimum along axis 1: ", m.min(axis=1))
print("Maximum along axis 0: ", m.max(axis=0))
print("Maximum along axis 1: ", m.max(axis=1))
print("\n")
print("Various Aggregates\n")
print("Sum of l        :", np.sum(l))
print("Product of l   :", np.prod(l))
print("Mean of l      :", np.mean(l))
print("Variance of l  :", np.var(l))
print("Standard Deviation of l :", np.std(l))
print("Median of l    :", np.median(l))
print("Percentile of l (50th) :", np.percentile(l, 50))
print("Percentile of l (90th) :", np.percentile(l, 90))
print("Correlation Coefficient of l with itself :", np.corrcoef(l, l))
print("Correlation Coefficient of l with itself (using np.corrcoef) :", np.corrcoef(l))